### ISSUE TITLE
Add better type support and out of the box type support

### ISSUE THREAD

**Issue by lloan** [lloan/next-authenticate#8]
**Components that require updating:**
- Next.js typings

**Tech to be used:**
- Next.js
- Typescript

**What is the current behavior:**
We explicitly importing types from index.d.ts to avoid name clashes (eg, Request is also a built in type for the built-in fetch API). Try to use out of the box types as much as possible without sacrificing type support for sake of making linter happy. 

**What is the new behavior:**
- [ ] Type the user context used throughout the app. 
- [ ] Type the _app React class-based component so the state is typed.
- [ ] Use built in typescript types for nextjs page components (whether functional or class-based) and API request and responses. [Next documentation here](https://nextjs.org/docs/basic-features/typescript). 

**Justification:** Typing the user state in the context and provider that wraps the app is most important as people will get better IDE support when accessing the user inside of their components. 

Notes: The API and pages could be updated incrementally without any problems 

Initialized by Jacob Goodwin.

**Comment by lloan** [comment]
Quite a bit of code is lacking type usage and some of the code is using `any` to get an initial testing version of next-authenticate out. A bit of cleanup is required for types throughout the project.

**Comment by Maxbrain0** [comment]
I'm actually not sure we need to wrap our app in a context in _app. I'm throwing this idea out there in case anybody's looked at this so far and wants to stop me. 

I believe we can pass the user onto the pageProps. Since we've decided to check the user with an http Post on every render of MyApp (the _app.tst component), I believe we can use the getInitialProps function (built into next) and then pass these props (properly typed) onto all pages. All pages could then access the user on the props.

> <Component {...pageProps} />


Anyhow, I'll see if it works initially, but it would be good to know if we might need the user in the AppContext for some other reason.

**Comment by lloan** [comment]
Is there a benefit from removing the context and using props to pass the data down instead of having it in one place? Figured it would be easier to control the flow.

**Comment by Maxbrain0** [comment]
I'm not sure yet. Just wanted to check that you hadn't already tried it. I'll dig around a bit and see what I learn. The main difference is the user would be available on page props instead of requiring a useContext inside of components. I guess the benefit of context is that it would be easier to use useContext in a component that is not a page, though I don't see that being a common use case at this point. 

I'll try to determine if

**Comment by lloan** [comment]
I wonder if this approach we have now would make it easier if a component has to for some reason modify the state of something and instead of having to push back from a child up back to the parent, we could just use context.

**Comment by Maxbrain0** [comment]
Yes, that would provide more flexibility. For example, in the other app I am working on, my Authorization Context also provides functions to the Provider (the via value property), for example to logout, which sets the user to undefined in the context. 

So, you now have me convinced to just keep the context.

**Comment by lloan** [comment]
Glad we discussed this - thanks for looking in to it, puts my mind at ease :).

**Comment by lloan** [comment]
When we're done with Spark, I will make sure to add any lessons learned there to this project to build from for other projects. Thanks @Maxbrain0 !
